name: gen-ai-chatbot-template
description: ''
version: 0.0.1
author: maciej@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: genaichatbottemplate
  parentArtefactID: maciej_prophecy
  buildSystem: wheel
  author: null
  createdAt: '2023-06-13 00:50:07'
pipelines:
  pipelines/web_vectorize:
    name: web_vectorize
    description: ''
    author: maciej@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-06-13 02:05:35'
    datasets:
      inputs:
      - datasets/web_bronze_content
      - datasets/web_silver_content_vectorized
      outputs:
      - datasets/all_vectors_silver
      - datasets/web_silver_content_vectorized
    subgraphs: []
    dependencies: {}
  pipelines/chatbot_batch:
    name: chatbot_batch
    description: ''
    author: maciej@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-06-13 05:00:18'
    datasets:
      inputs:
      - datasets/question_seed
      - datasets/web_silver_content_vectorized
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/chatbot_live:
    name: chatbot_live
    description: ''
    author: maciej@prophecy.io
    mode: stream
    artefactID: ''
    language: python
    createdAt: '2023-06-22 05:25:43'
    datasets:
      inputs:
      - datasets/slack_chat
      - datasets/web_silver_content_vectorized
      outputs:
      - datasets/bot_messages_target
    subgraphs: []
    dependencies: {}
  pipelines/web_ingest:
    name: web_ingest
    description: ''
    author: maciej@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-06-22 05:27:53'
    datasets:
      inputs:
      - datasets/web_bronze_sitemap
      - datasets/web_bronze_url
      outputs:
      - datasets/web_bronze_content
      - datasets/web_bronze_sitemap_raw
    subgraphs: []
    dependencies: {}
  pipelines/testPDF:
    name: testPDF
    description: ''
    author: bobw@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-09-23 18:41:33'
    datasets:
      inputs:
      - datasets/pdf_source
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/web_bronze_sitemap_raw:
    name: web_bronze_sitemap_raw
    description: ''
    author: maciej@prophecy.io
    createdAt: '2023-06-13 01:53:47'
    mode: batch
    physicalDatasets:
      dev_product:
        fabricId: 2
        datasetType: File
        description: ''
        author: maciej@prophecy.io
        createdAt: '2023-06-13 01:53:47'
  datasets/web_bronze_sitemap:
    name: web_bronze_sitemap
    description: ''
    author: maciej@prophecy.io
    createdAt: '2023-06-13 01:56:28'
    mode: batch
    physicalDatasets:
      dev_product:
        fabricId: 2
        datasetType: File
        description: ''
        author: maciej@prophecy.io
        createdAt: '2023-06-13 01:56:28'
  datasets/web_bronze_content:
    name: web_bronze_content
    description: ''
    author: maciej@prophecy.io
    createdAt: '2023-06-13 02:01:38'
    mode: batch
    physicalDatasets:
      dev_product:
        fabricId: 2
        datasetType: Database
        description: ''
        author: maciej@prophecy.io
        createdAt: '2023-06-13 02:01:38'
  datasets/web_silver_content_vectorized:
    name: web_silver_content_vectorized
    description: ''
    author: maciej@prophecy.io
    createdAt: '2023-06-13 04:20:06'
    mode: batch
    physicalDatasets:
      dev_product:
        fabricId: 2
        datasetType: Database
        description: ''
        author: maciej@prophecy.io
        createdAt: '2023-06-13 04:20:06'
  datasets/all_vectors_silver:
    name: all_vectors_silver
    description: ''
    author: maciej@prophecy.io
    createdAt: '2023-06-13 04:38:14'
    mode: batch
    physicalDatasets:
      dev_product:
        fabricId: 2
        datasetType: Warehouse
        description: ''
        author: maciej@prophecy.io
        createdAt: '2023-06-13 04:38:15'
  datasets/question_seed:
    name: question_seed
    description: ''
    author: maciej@prophecy.io
    createdAt: '2023-06-13 05:18:30'
    mode: batch
    physicalDatasets:
      dev_product:
        fabricId: 2
        datasetType: File
        description: ''
        author: maciej@prophecy.io
        createdAt: '2023-06-13 05:18:30'
  datasets/slack_chat:
    name: slack_chat
    description: ''
    author: maciej@prophecy.io
    createdAt: '2023-06-20 04:50:15'
    mode: stream
    physicalDatasets:
      dev_product:
        fabricId: 2
        datasetType: WebApp
        description: ''
        author: maciej@prophecy.io
        createdAt: '2023-06-20 04:50:15'
  datasets/bot_messages_target:
    name: bot_messages_target
    description: ''
    author: maciej@prophecy.io
    createdAt: '2023-06-20 04:50:58'
    mode: stream
    physicalDatasets:
      dev_product:
        fabricId: 2
        datasetType: WebApp
        description: ''
        author: maciej@prophecy.io
        createdAt: '2023-06-20 04:50:58'
  datasets/web_bronze_url:
    name: web_bronze_url
    description: ''
    author: maciej@prophecy.io
    createdAt: '2023-06-24 20:23:30'
    mode: batch
    physicalDatasets:
      db_product:
        fabricId: 1777
        datasetType: WebApp
        description: ''
        author: maciej@prophecy.io
        createdAt: '2023-06-24 20:23:30'
  datasets/pdf_source:
    name: pdf_source
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-09-23 18:44:23'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-09-23 18:44:23'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2023-06-13 00:50:07'
  udfs:
    udfs/scrape_text:
      name: scrape_text
      description: ''
      tags: []
      inputs: []
      outputs: []
      author: maciej@prophecy.io
      createdAt: '2022-12-15 18:04:50'
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- type: plibMaven
  modifiedAt: '2024-09-23T18:41:35.131123Z'
  name: plibMaven
  version: 8.1.8
  id: '438480919'
  createdAt: '2024-09-23T18:41:35.131023Z'
  enabled: true
  entity: Project
- type: plibPypi
  modifiedAt: '2024-09-23T18:41:35.131198Z'
  name: plibPypi
  version: 1.9.14
  id: '2104604227'
  createdAt: '2024-09-23T18:41:35.131173Z'
  enabled: true
  entity: Project
- type: pypi
  package: prophecy-spark-ai==0.1.8
  name: Prophecy Spark AI (Python)
  enabled: true
  id: KfvmV
  entity: Project
  description: spark_ai
  scope: Project
  modifiedAt: '2024-09-23T19:08:08.834Z'
  editable: true
  createdAt: '2024-09-23T19:02:14.558Z'
- type: coordinates
  coordinates: io.prophecy:spark-ai_2.12:0.1.8
  name: Prophecy Spark AI
  enabled: true
  id: xs0D8
  entity: Project
  scope: Project
  modifiedAt: '2024-09-23T19:04:54.982Z'
  editable: true
  createdAt: '2024-09-23T18:56:51.664Z'
  repo: https://mvnrepository.com/artifact/io.prophecy/spark-ai
  exclusions: []
projectDependencies:
  '12656':
    projectUID: 12656
    projectName: ProphecyStreamingPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12656.git&subPath=
    version: 0.0.3
    isDefault: true
    author: null
    createdAt: '2024-09-23 18:10:32'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2024-09-23 18:10:32'
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.28
    isDefault: true
    author: null
    createdAt: '2024-09-23 18:10:32'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
